# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
- project:
    templates:
      - docs-on-readthedocs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - openstack-cover-jobs
    vars:
      rtd_webhook_id: '86525'
      rtd_project_name: 'airship-spyglass'
    check:
      jobs:
        - openstack-tox-pep8
        - spyglass-dependency-vulnerability-check
        - spyglass-docker-build-gate-ubuntu_xenial
        - spyglass-docker-build-gate-ubuntu_bionic
        - spyglass-docker-build-gate-opensuse
    gate:
      jobs:
        - openstack-tox-pep8
        - spyglass-dependency-vulnerability-check
        - spyglass-docker-build-gate-ubuntu_xenial
        - spyglass-docker-build-gate-ubuntu_bionic
        - spyglass-docker-build-gate-opensuse
    post:
      jobs:
        - spyglass-upload-git-mirror
        - spyglass-docker-publish-ubuntu_xenial
        - spyglass-docker-publish-ubuntu_bionic
        - spyglass-docker-publish-opensuse

- nodeset:
    name: spyglass-single-node
    nodes:
      - name: primary
        label: ubuntu-xenial

- job:
    name: spyglass-dependency-vulnerability-check
    parent: openstack-tox
    voting: false
    timeout: 600
    nodeset: spyglass-single-node
    vars:
      tox_envlist: safety

- job:
    name: spyglass-docker-build-gate-ubuntu_xenial
    timeout: 1800
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: spyglass-single-node
    vars:
      publish: false
      distro: ubuntu_xenial
      tags:
        dynamic:
          patch_set: true

- job:
    name: spyglass-docker-build-gate-ubuntu_bionic
    timeout: 1800
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: spyglass-single-node
    vars:
      publish: false
      distro: ubuntu_bionic
      tags:
        dynamic:
          patch_set: true

- job:
    name: spyglass-docker-build-gate-opensuse
    timeout: 1800
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: spyglass-single-node
    vars:
      publish: false
      distro: opensuse_15
      tags:
        dynamic:
          patch_set: true

- job:
    name: spyglass-docker-publish-ubuntu_xenial
    timeout: 1800
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: spyglass-single-node
    secrets:
      - airship_spyglass_quay_creds
    vars:
      publish: true
      distro: ubuntu_xenial
      tags:
        dynamic:
          branch: true
          commit: true
        static:
          - latest

- job:
    name: spyglass-docker-publish-ubuntu_bionic
    timeout: 1800
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: spyglass-single-node
    secrets:
      - airship_spyglass_quay_creds
    vars:
      publish: true
      distro: ubuntu_bionic
      tags:
        dynamic:
          branch: true
          commit: true
        static:
          - latest

- job:
    name: spyglass-docker-publish-opensuse
    timeout: 1800
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: spyglass-single-node
    secrets:
      - airship_spyglass_quay_creds
    vars:
      publish: true
      distro: opensuse_15
      tags:
        dynamic:
          branch: true
          commit: true
        static:
          - latest

- secret:
    name: airship_spyglass_quay_creds
    data:
      username: !encrypted/pkcs1-oaep
        - vW9FvKGXcUOLEaq8gjcbfrUXZWen5he2FfNVs4IIa7PtXMToiSbw4+07ZpkqhmgLAvVJ1
          xCk274kPoYztCEOODyHUCJQVkROBhb2Phrzm1RDq+oNssDWgeUIzHf1FZmXJOZCRYMhrz
          I3xg8+lWRlKeFS6u8M10pkd8iW5Gt7u19gW4dinerOnqyhLKoJfPQ00pzs1lIxAh0r89e
          ZXNJr4K0n8pMp43ihZN9EHcU7zGb8kxPqUTt6NrXejaWDm3IPO/TbSnGTOLhctcMV7fFa
          MWim7JxIxwdegoYGv9hMoJhXMMRFeUVy/iNFA9aZCl9TR01oHwXNOdv94pJWyNDmFG2Cy
          BxAQHtXVZdQlRpcmqcrS3iIrEkuyoXyGjaYqrMX/OpPdmmPnvL2Gl4QQjfRo2eAc5Ma6M
          4Iuq1zv2ncn//NBTvnFGRF5P0Late+6ZPC4j/UVeozT0u4wO8T/C+js3nhNnjhvDzsWXm
          KLlO1O0KXlCAN8GVvVH/0yMxFqjE3xN5UK+3EX4/6Qv6ZYp9LqQ6BwNmH/uFEuDGKqviF
          kF5mgza/c3+YV8ig9zGBzJcMmjzB5EZ/SDSFNgIne7ky60jyZNaS7EZgb2TmBHcpd8oXn
          JdQXq4maP1w6DRFgbxnfZMTI76UMrzSxR0jKskagOJFFqeUjr9zn+aV07E+ijc=
      password: !encrypted/pkcs1-oaep
        - bORgw0TIMX1NVS2MnFrL10ZzxcXQ76ndpziFKxGLFgB1b+9D24HylcAs64SPw3sT5cSGR
          TUqOtWfPSWCnXWssPtrlUVIwUIOZjUq5DhJ8dw8gjrKGx9p1nuVRZVLDw9PZe7yTPVvM9
          MJugMrN/WdIlzYneiT3iZy0M9lx7PkB32MNVh/hfsRCCCnY3MnNcKJo5FHXJYcwIrFao+
          oR+YKJGTxNPeO7fxQndZH43dbuM3yv4CAOb8wumqyufiBCdiRLVLeEl4oEGhHZOSu2G+U
          jSzUmPSYCWM/aAaHYeiDrf6ZCIKlV6OEFxf9Ta7Fnvxth6nZJHub0xTFfvPwccUAlP8Y4
          80DlE0/ApEN4WAt3fTImUh4m/RcmZ1fS15qf+SbWGx8mIqk10StJIDGQViqyLpcOF3s2F
          BOLzcyDz4Lp0YudBs1i0YOtNB7Rr6WiJoHYZTILj47f/F1Uz/uXFaR7Kqg+GFRl+OvaI0
          V3rDRQ6VlEnFYOrY4UMypxY1qSn4xRvYDX3ZtNToe+WOazTABT6b4Xonh7kKoD+Vmysn3
          mc6gexwzmBflO+yyaokpIzU5rIP5mQ6yWBSyoXVO94Ix11VdL3COQppfg7KO1/8gW+Kmh
          MSQhHBn34oof6CaDpNSDlvIdnl/MmGmfMiSB5sdTbzho7VL9TrjKh0buI1IDXg=

- job:
    name: spyglass-upload-git-mirror
    parent: upload-git-mirror
    description: Mirrors airship/spyglass to airshipit/spyglass
    vars:
      git_mirror_repository: airshipit/spyglass
    secrets:
      - name: git_mirror_credentials
        secret: spyglass-airshipit-github-secret
        pass-to-parent: true

- secret:
    name: spyglass-airshipit-github-secret
    data:
      user: git
      host: github.com
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
      ssh_key: !encrypted/pkcs1-oaep
        - OmZT4o7e8ISwzDXY7oFR9PoGVER0YBiFbj1580PSwLj2Vx6e9JoGYOJNAGhb3n0V5x+ve
          ioSMwZEHgvUambFsau3flBxkNOH88BiohLJd25Zks68PPQ99qbY2/C519zH+QXtoWv9D2
          ggR1Rfzj2DNlBNHnX4uDin/QLQhxkoetOCiXV2C2H1kiXeEVlyGW+ws3Yihqz3+HQUP2D
          vNRsg8OXk+9JpfBaWSrQ42MX1Uqp1q9ykUAPmenttTiC3msPXFhgV+fUX4mgmd4Fmb20l
          C2MMxCdZKsg6t8Y2bdCFzDYqquwPagDjszNlnYS2OJ4hwj/ANbCrZXwSN4bAV72O2jKla
          L3rp/nRRvwWfZ080QuuGzvmcaVT89YWt+rR5SBwen6GIDW+876HcM6zoD2rWtFc27rWg9
          rBH+fGjDINr3DrFeCCQhfLqT4L8E1WYgjsIjD6ZO2mGT0ZdyIk4FPdtxwunnoPvRTY7Ks
          eArLnMkobwu45I3Jw/rmuwBx013KJ1tbn30Hv0w/6MB8NaOOqsLAXcs6MSBu0Hj8S0bvS
          Aamd2btGgJYBjfXyFvrSbF76kLXI3XeEWOplDkgMPuEytgMkvCPbS65k53UUhl/2QTCtv
          mLIF+9NToorIbbdVoARHgTjX8gxu7tSpgr4Lq8N/79JXX7C87tBibbHn56Wp+k=
        - GQg7+oUbph7zjr5mzkFn+zRHKgOwXC7qB10v9T0YjNPPmCN+gbos2OgJ/pogGVkXIfzrN
          HBqy0+79T5cGSugfoU1rNkSD7g6cciBoAqLJ3jTXIYeOmQsl61eW9OweejheMKUK2sLFB
          /+54LmUtvx1/ldGWUD1z1XE/oToF9QOZplR0ugQl9bE1Mzrq1BwlDCRTsho8aPQ8jCqEn
          yRJ2bCrK8LuwuXeCgzFD/njJCiKrOecZuXTn0vkqgBE0xaAorlJ1dKpRzZaFW6WNdPF+f
          zQjmx3dTrYQq+XDju9IvXEvnrOp01MczieNQBz2NqGUG00ALvFHDISbqZ1y+dVqiwf+mc
          Y+W9PWXY/iu07KdOZ3Frnx3Wuvbztu8EWZicfhNP9e7tG5HD6zFIirKx78SlMqGSmLrcQ
          u5heygVJqTEV41NULIc+fAYb5WS0dF/8lnqBtLTj55YJM5e2SJBuX3BFfUDDfmgNFDiL4
          QD6DJ0y5gs8JMmjHB3K29sgG8QyvfB8FENGravDOWm82wHJoAQjFghIA98tSl34Rg8vJA
          mdgcmoepn0fSfP/tImHQOLejw/xMOowCKhG1cUvX1YGhAacM5wHdkbQI5GI+qGk1B5GzM
          Iy3ybJnWlaEsjJIYYw0cEJQ3IjrhWX/E7ebm6g2u+nvXAMtqOoKsUEWi81GTb0=
        - lN8fWgjUy96y9oInpoQhNyLN6xoKkt+2FUpwOkC3dm3DGdXTUqZjU4ZqUChai3EQdGJYz
          viYSXrobgQBX5VXAke4mnXuYPzWp9PGCH+Mbv8nsKq05Om3/K5HMnXvO7hSCMWqN7S85J
          dsCc166bm3iZVNlSZ6bOC7hO5ai1qSdaocwzRWnFMjZQtGUprDp52Ei9r8Ii9jVSCuVbb
          zAH+vpQt9ij4bo+EFxYApsiryBXZdpxxBLD5CQZDQ6Nt2f3SLv0Vf8ezhX9URaQh1Az/q
          uOjJ4RgazsdlJN/3LCZJ12Vud5Tszj0iyt3tfrZo3mJ0CLri0hGuieAAlom+KiUrzj3nc
          AJ7R15TSpEsIiBrnWZ1S7MgWTrNLXR7MBWZ5s8AQJAfYp/fBrxZdV/lspmuRg1Q00SqEs
          opg7/ABTSVkUSViXDp01Hod9nHwNt2r/+zQbPJVIwZHPYqCAZvGSHen1nP7NmCxxQkQL2
          7qgVHyCMwFfDVhEsX453Pc7MLlvBgB1aNlg2Au6SchlqNEMFQ98ZEDhZW/9jjEaJTMCuI
          2d4Tf/MSer81pZ1MkWXaTp69WeIGbnwmWx7ZIyIX0U8mR6IuSdLwEihTM1g6kZG4JIHwv
          EDKndDGC8L5F00nRcM1m4S8RLiGh9628jJUDmlomkraNegZjzHC7KMqPuLUqGE=
        - xYm7B0+O/LKGGE0fnb04DkVvqluHH7ePTSN9WQDdUBWo1bhYXtXC3JX8Rx29yKR689iJt
          qAy+Oz8RLowX2nzCDNASqsMrkXFJ3ljCD+kbTqrVbTyTxhNCJCsexRWjkn4F0cb5D0GyP
          GQwO+7GCmum4z0dCBnFc1BY78UQFtAO/zi5Lij2YDXvPyap85rrifflZlzV4Gp2Vd5ExO
          dSkq04Sc0VJaD8Q9yPnbLSLzT5JWAseGr05ywscJsykXfQvAyC4TleJgpgqcqFoLhGGBU
          fMzCiiHmJ+RTbduHNTWJUa3CQCiagay/gAgfmcXjH3KEmq3oqXkCCX/xngob1W2eh4c0/
          5vfv0dwca2u96M6BmOtPmHARxWKhaiIwEnRM2VDX2xf4mgmk0AU7Di1UqnYCmuVdbUPbX
          dDZ3CMdtk+48tirMJke0iaXLXvEU4U/2qhfGSH4SnaXjy2tN152vx1DwBH3ngKa7tqFKp
          KWtmDNCjPgWycqsyYrBAheZm9k6/efjzywsPWpoqGxwNHFNZyRaxL/HxZOA7oPzkFEvDz
          lWJMaNxrDCjEYWDOBndKGL4NX8+upX18++tnSIwSI/ssu0zO8qydt3x0kTYUBJlbggQWE
          N4UOKKnEq4HanVis/RxNMAjALvY5Ni5knKVtP8VwOgHQoAkGI/CsieVtLQFWrQ=
